image: ghcr.io/home-assistant/{arch}-hassio-audio
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.23-2026.02.0
  amd64: ghcr.io/home-assistant/amd64-base:3.23-2026.02.0
cosign:
  base_identity: https://github.com/home-assistant/docker-base/.*
  identity: https://github.com/home-assistant/plugin-audio/.*
args:
  PULSE_VERSION: "17.0"
labels:
  io.hass.type: audio
  org.opencontainers.image.title: Home Assistant Audio Plugin
  org.opencontainers.image.description: Home Assistant Supervisor plugin for Audio
  org.opencontainers.image.source: https://github.com/home-assistant/plugin-audio
  org.opencontainers.image.authors: The Home Assistant Authors
  org.opencontainers.image.url: https://www.home-assistant.io/
  org.opencontainers.image.documentation: https://www.home-assistant.io/docs/
  org.opencontainers.image.licenses: Apache License 2.0
